// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuNp_Sw12hdKxmhnIsfHV7Ux_5JQpCeO4',
    appId: '1:818698121063:web:33d61124c841115b83c9c2',
    messagingSenderId: '818698121063',
    projectId: 'notes-25a9c',
    authDomain: 'notes-25a9c.firebaseapp.com',
    storageBucket: 'notes-25a9c.appspot.com',
    measurementId: 'G-BDVCHZ0RCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoVPk_9ZxwbijYCHexUTRu0SWgQqbkhUg',
    appId: '1:818698121063:android:3e9a63d6697ca28883c9c2',
    messagingSenderId: '818698121063',
    projectId: 'notes-25a9c',
    storageBucket: 'notes-25a9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDavnLlqSu3q3X9Z9jU53-DVZnN0ck8Fs0',
    appId: '1:818698121063:ios:69ed8b7760e1ea0983c9c2',
    messagingSenderId: '818698121063',
    projectId: 'notes-25a9c',
    storageBucket: 'notes-25a9c.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDavnLlqSu3q3X9Z9jU53-DVZnN0ck8Fs0',
    appId: '1:818698121063:ios:69ed8b7760e1ea0983c9c2',
    messagingSenderId: '818698121063',
    projectId: 'notes-25a9c',
    storageBucket: 'notes-25a9c.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuNp_Sw12hdKxmhnIsfHV7Ux_5JQpCeO4',
    appId: '1:818698121063:web:1f3b290127c4523983c9c2',
    messagingSenderId: '818698121063',
    projectId: 'notes-25a9c',
    authDomain: 'notes-25a9c.firebaseapp.com',
    storageBucket: 'notes-25a9c.appspot.com',
    measurementId: 'G-GZ44SGLQSG',
  );
}
